framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # The default cache adapter is now tagged_adapter wrapping filesystem
        # To use the filesystem adapter directly:
        app: cache.adapter.filesystem

        # Redis configuration (uncomment to use)
        #app: cache.adapter.redis
        #default_redis_provider: 'redis://localhost'

        # APCu configuration (uncomment to use)
        #app: cache.adapter.apcu

        # Memcached configuration (uncomment to use)
        #app: cache.adapter.memcached
        #default_memcached_provider: 'memcached://localhost'

        # Using the tagged adapter (default in Symfony 7)
        #app: cache.adapter.tagged

        # For system cache separate from app data
        system: cache.adapter.system

        # Namespaced pools use the above "app" backend by default
        #pools:
        #    my.dedicated.cache:
        #        adapter: cache.adapter.filesystem
        #        tags: true