security:
    # Use the modern password hasher with higher algorithm settings
    password_hashers:
        App\Entity\User:
            algorithm: auto
            cost: 15  # Higher cost means more secure but slower verification

    # Define user providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    # Firewall configuration
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            # Use the newer login form authenticator instead of form_login
            custom_authenticator: App\Security\LoginFormAuthenticator

            # Remember me functionality
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week

            # Logout configuration
            logout:
                path: logout
                target: homepage # Redirect after logout

    # Access control for URL patterns
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
